### ISSUE TITLE
Deleting Bug

### ISSUE THREAD

**Issue by Star-Cyber3** [Star-Cyber3/List#18]
**Expected behavior**
Expected: When all are deleted via the x buttons, the clear all button should be greyed out.

**Comment by AmjadNoor** [comment]
Hi @Star-Cyber3 , can use assign me in this bug issue because I solved it. If you assign me then I pull my pull request.
Thanks.

**Comment by AmjadNoor** [comment]
@Star-Cyber3 , Please if you read this comment then reply.

**Comment by Star-Cyber3** [comment]
Hello Amjad, 
If you think the problem is the commented thing, it is not, that was a failed test.

**Comment by AmjadNoor** [comment]
@Star-Cyber3  I almost done but there is one problem. If you have discord or twitter then give me link that I can talk to you. Thank you.

**Comment by Star-Cyber3** [comment]
I do not have any of these, though we can talk in the discussion.

**Comment by Star-Cyber3** [comment]
Hello?

**Comment by Star-Cyber3** [comment]
Hello?

**Comment by AmjadNoor** [comment]
Yes I am here talk to me.

**Comment by Star-Cyber3** [comment]
We can just talk here

**Comment by Star-Cyber3** [comment]
I will be available at 3:30

**Comment by Star-Cyber3** [comment]
I just want to know if you are still going to work on this as it has been a while since you have committed to either your fork or my my repository.

**Comment by AmjadNoor** [comment]
@Star-Cyber3 I don't understand what you are telling.

**Comment by AmjadNoor** [comment]
I am working on it yesterday but it can't solve with me I try  more then 50 times.

**Comment by Star-Cyber3** [comment]
Yeah, I was trying too without success.

**Comment by Star-Cyber3** [comment]
😢

**Comment by Star-Cyber3** [comment]
@AmjadNoor  I think I have solved it. #31

**Comment by Star-Cyber3** [comment]
Please look at it and tell me if it is good.

**Comment by Star-Cyber3** [comment]
@AmjadNoor Hello?

**Comment by Star-Cyber3** [comment]
#31

**Comment by Star-Cyber3** [comment]
Hello?

**Comment by AmjadNoor** [comment]
Hi

**Comment by AmjadNoor** [comment]
Sorry for late response.
