### ISSUE TITLE
Adding Local storage 

### ISSUE THREAD

**Issue by AmjadNoor** [Star-Cyber3/List#34]
## Describe the solution you'd like
I want to add local storage that when an user create to do list. User is not able to lost their to do list. If he delete then it will be delete from his local storage.

If you want this feature then assign it to me.
Thanks 🤟🏻

**Comment by Star-Cyber3** [comment]
Yes that would be awesome as it would make my page better. I have been trying to experiment though I don't know advanced JavaScript so I don't know how to do this. Thanks

**Comment by Star-Cyber3** [comment]
FYI I have discord now. My username is hi1#9359.

**Comment by AmjadNoor** [comment]
Ok

**Comment by AmjadNoor** [comment]
You not accepting friend request. If you want to correct this issue then go to setting and change it. So please send me friend request my id is AmjadNoor#2368
![Screenshot_2021-04-26-22-09-03-37](https://user-images.githubusercontent.com/56997478/116119413-0c0b1180-a6dc-11eb-9f9f-2a9bb5a03e9a.jpg)

**Comment by Star-Cyber3** [comment]
Sorry try again now
